# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for npm publish --provenance
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18
          registry-url: https://registry.npmjs.org/


      - run: pnpm install
      - run: pnpm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
